### PR TITLE
Update docker-compose.yaml

### PR DESCRIPTION
**Pull request by niku2676**

### CODE REVIEW

**Comment by g0ldyy** [comment]
you just leaked your jaxkett server url + API key
please delete this

**Comment by niku2676** [comment]
I know I misslicked and I dont know how to delete it lol

**Comment by niku2676** [comment]
> you just leaked your jaxkett server url + API key please delete this

I cant delete it you need to deleted. Can you delete it for me pls

**Comment by g0ldyy** [comment]
make your repo private.

**Comment by niku2676** [comment]
I did but its still here. You need to delete it

**Comment by niku2676** [comment]
grafik

**Comment by g0ldyy** [comment]
I can't delete a pull request, please reset your jackett api key.

**Comment by niku2676** [comment]
you can do it here: https://support.github.com/contact there is an AI bot which does it automatically

**Comment by g0ldyy** [comment]
> you can do it here: https://support.github.com/contact there is an AI bot which does it automatically

done

**Pull request closed without merging**
